sudo: required
services:
  - docker
before_install:
  - docker build -t ahismail/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ahismail/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-092812100371"
  bucket_path: "docker-react"
  on:
    branch: master
  